In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('./taylor_swift_lyrics.csv',encoding = 'latin-1')

In [3]:
df.head(11)

artist         album track_title  track_n  \
0   Taylor Swift  Taylor Swift  Tim McGraw        1   
1   Taylor Swift  Taylor Swift  Tim McGraw        1   
2   Taylor Swift  Taylor Swift  Tim McGraw        1   
3   Taylor Swift  Taylor Swift  Tim McGraw        1   
4   Taylor Swift  Taylor Swift  Tim McGraw        1   
5   Taylor Swift  Taylor Swift  Tim McGraw        1   
6   Taylor Swift  Taylor Swift  Tim McGraw        1   
7   Taylor Swift  Taylor Swift  Tim McGraw        1   
8   Taylor Swift  Taylor Swift  Tim McGraw        1   
9   Taylor Swift  Taylor Swift  Tim McGraw        1   
10  Taylor Swift  Taylor Swift  Tim McGraw        1   

                                                lyric  line  year  
0                 He said the way my blue eyes shined     1  2006  
1         Put those Georgia stars to shame that night     2  2006  
2                              I said, "That's a lie"     3  2006  
3                         Just a boy in a Chevy truck     4  2006  
4                That had a tendency of gettin' stuck     5  2006  
5                               On backroads at night     6  2006  
6    And I was right there beside him all summer long     7  2006  
7   And then the time we woke up to find that summ...     8  2006  
8                       But when you think Tim McGraw     9  2006  
9                   I hope you think my favorite song    10  2006  
10                The one we danced to all night long    11  2006

In [4]:
songs = df.groupby('track_title').agg({'lyric': lambda x: " ".join(x),
                                       'year': 'mean'}).reset_index()
print(songs)

               track_title                                              lyric  \
0         ...Ready for It?  Knew he was a killer first time that I saw him...   
1                       22  It feels like a perfect night to dress up like...   
2   A Perfectly Good Heart  Why would you wanna break a perfectly good hea...   
3    A Place In This World  I don't know what I want, so don't ask me Caus...   
4             All Too Well  I walked through the door with you, the air wa...   
..                     ...                                                ...   
89          Wildest Dreams  He said, "Let's get out of this town Drive out...   
90              Wonderland  Flashing lights and we Took a wrong turn and w...   
91         You Are in Love  One look, dark room, meant just for you Time m...   
92      You Belong With Me  You're on the phone with your girlfriend, she'...   
93        You're Not Sorry  All this time I was wasting hoping you would c...   

    year  
0   2017  
1   2

In [5]:
'''
import csv
v = open('C:\\Users\\user1\\taylor_swift_lyrics.csv')
reader = csv.reader(v,'r')
row0 = reader.next()
row0.append('Category')
print(row0)

'''
'''
import csv
f1 = open('C:\\Users\\user1\\taylor_swift_lyrics.csv', 'r')
f2 = open('C:\\Users\\user1\\taylor_swift_lyrics.csv_updated', 'w')
reader = csv.reader(f1)
writer = csv.writer(f2)
headers = next(reader)
headers.append("Category")
print(headers)
writer.writerow(headers)

f1.close()
f2.close()
'''
'''
for row in reader:
    row.append(new data for my new header)
    writer.writerow(row)
    open( input_file, 'r' )
'''

"\nfor row in reader:\n    row.append(new data for my new header)\n    writer.writerow(row)\n    open( input_file, 'r' )\n"

In [6]:
pd.options.display.max_colwidth = 5000

In [7]:
songs.head()


track_title  \
0        ...Ready for It?   
1                      22   
2  A Perfectly Good Heart   
3   A Place In This World   
4            All Too Well   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                lyric  \
0                                                                                                                                                                                                                                                                                                               Knew he was a killer first time that I saw him Wondered how many girls he had loved and left haunted But if he's a ghost, then I can be a phantom Holdin' him for ransom, some Some boys are tryin' too hard, he don't try at all though Younger than my exes, but he act like such a man, so I see nothing better, I keep him forever Like a vendetta-ta I, I, I see how this is gon' go Touch me and you'll never be alone I-Island breeze and lights down low No one has to know In the middle of the night, in my dreams You should see the things we do, baby In the middle of the night, in my dreams I know I'm gonna be with you So I take my time Are you ready for it? Knew I was a robber first time that he saw me Stealing hearts and running off and never sayin' sorry But if I'm a thief, then he can join the heist, and We'll move to an island, and And he can be my jailer, Burton to this Taylor Every love I've known in comparison is a failure I forget their names now, I'm so very tame now Never be the same now, now I, I, I see how this is gon' go Touch me and you'll never be alone I-Island breeze and lights down low No one has to know (no one has to know) In the middle of the night, in my dreams You should see the things we do, baby In the 

In [8]:
len(songs)

94

In [9]:
artist = df[df['artist'] == 'artist-name']
print(artist)

Empty DataFrame
Columns: [artist, album, track_title, track_n, lyric, line, year]
Index: []


In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [11]:
import nltk
from nltk.corpus import stopwords

In [12]:
import nltk
#nltk.download('stopwords')

In [13]:
stop_words = stopwords.words('english')

In [14]:
stop_words.extend(['back','said','come','things','get','oh','one','yeah','place','would','like','know','stay','go','let','cause'])

In [15]:
vectorizer = TfidfVectorizer(stop_words = stop_words, min_df = 0.1)

In [16]:
import numpy as np
print((songs['lyric']).size)
print((songs['lyric']).shape)

print(songs['lyric'].ndim)
print(type(songs['lyric']))
tfidf = vectorizer.fit_transform(songs['lyric'])
print(songs['lyric'])

94
(94,)
1
<class 'pandas.core.series.Series'>
0                                                                                                                                                                                                                                                                                                                  Knew he was a killer first time that I saw him Wondered how many girls he had loved and left haunted But if he's a ghost, then I can be a phantom Holdin' him for ransom, some Some boys are tryin' too hard, he don't try at all though Younger than my exes, but he act like such a man, so I see nothing better, I keep him forever Like a vendetta-ta I, I, I see how this is gon' go Touch me and you'll never be alone I-Island breeze and lights down low No one has to know In the middle of the night, in my dreams You should see the things we do, baby In the middle of the night, in my dreams I know I'm gonna be with you So I take my time Are you rea

In [17]:
from sklearn.decomposition import NMF

In [18]:
nmf = NMF(n_components = 6)

In [19]:
topic_values = nmf.fit_transform(tfidf)


In [20]:
for topic_num, topic in enumerate(nmf.components_): 
    message = "Topic #{}: ".format(topic_num + 1) 
    message += " ".join([vectorizer.get_feature_names()[i] for i in topic.argsort()[:-11 :-1]])
    print(message)

Topic #1: love beautiful way never knew waiting feel say see alone
Topic #2: ever never getting remember still want see gonna could old
Topic #3: wanna good first break feeling end way well miss heart
Topic #4: baby time sorry night bad see dancing every dreams tell
Topic #5: think gone dress hope head rain could better best home
Topic #6: girl got home look tell long say want forever trying


In [21]:
topic_labels = ['love','reminiscing','breakups','party','homesick','independence']


In [22]:
print(topic_values )
n = len(topic_values)

[[0.05409581 0.09051944 0.         0.46221529 0.         0.        ]
 [0.02068458 0.         0.08533201 0.26504007 0.05321171 0.        ]
 [0.         0.         0.69589062 0.         0.         0.        ]
 [0.         0.03252125 0.01716318 0.         0.         0.46432486]
 [0.         0.19107021 0.08221554 0.07181936 0.0617459  0.14936764]
 [0.07350437 0.01046525 0.11950587 0.04366255 0.0850736  0.0775655 ]
 [0.0418878  0.11683189 0.         0.35272068 0.06530338 0.        ]
 [0.         0.         0.         0.34265645 0.04918794 0.17497574]
 [0.03090564 0.23868921 0.0414435  0.         0.34097676 0.00665312]
 [0.02568505 0.08980738 0.0369921  0.         0.41070054 0.02701815]
 [0.10964897 0.         0.04032251 0.19191603 0.         0.35499185]
 [0.0538382  0.12254745 0.03192469 0.23198262 0.03912009 0.        ]
 [0.         0.09319621 0.         0.074461   0.02376668 0.06860677]
 [0.09058617 0.15456417 0.0097403  0.14393967 0.         0.0049022 ]
 [0.         0.00606567 0.        

In [23]:
#avg_val[i] = avg_val[i]/n

In [24]:
import statistics
import numpy as np
a  = topic_values[ : , : ].tolist()
'''
statistics.mean(a[ : ,0:1])'''
avg_val = [0 for i in range(6)]
'''
for i in range(5):
    for j in range(n):
        avg_val[i] = avg_val[i] + topic_values[j][i]
'''

list_val1 = []
list_val2= []
list_val3= []
list_val4= []
list_val5= []
list_val6 = []
for j in range(n):
    list_val1.append(topic_values[j][0])
    list_val2.append(topic_values[j][1])
    list_val3.append(topic_values[j][2])
    list_val4.append(topic_values[j][3])
    list_val5.append(topic_values[j][4])
    list_val6.append(topic_values[j][5])
        
#rint(statistics.median(list_val1))
#rint(avg_val)

print(max(list_val1),max(list_val2),max(list_val3),max(list_val4),max(list_val5),max(list_val6))

avg_val[0] = np.quantile(list_val1,.75)
avg_val[1] = np.quantile(list_val2,.75)
avg_val[2] = np.quantile(list_val3,.75)
avg_val[3] = np.quantile(list_val4,.75)
avg_val[4] = np.quantile(list_val5,.75)
avg_val[5] = np.quantile(list_val6,.75)

'''
for i in range(5):
    avg_val[i] = avg_val[i]\\\n
    '''

print("")
print(avg_val)
#rint(sum(avg_val)/(n*5))'''

0.3557565418281546 0.6780681550051137 0.6958906238420561 0.4882438955972695 0.5890247374853824 0.6958987759077706

[0.10810605275281546, 0.12122291551981593, 0.05976526081935554, 0.19428346232058452, 0.08697287866999256, 0.1309982651641643]


In [25]:
a


[[0.054095814215263945,
  0.09051943757330451,
  0.0,
  0.4622152864652508,
  0.0,
  0.0],
 [0.020684578502653452,
  0.0,
  0.08533201097996831,
  0.26504007014570047,
  0.05321170978474521,
  0.0],
 [0.0, 0.0, 0.6958906238420561, 0.0, 0.0, 0.0],
 [0.0,
  0.03252125414399407,
  0.017163175645038317,
  0.0,
  0.0,
  0.4643248589983676],
 [0.0,
  0.19107020778420664,
  0.08221553711471169,
  0.07181935593715606,
  0.06174590116772492,
  0.14936763714842655],
 [0.0735043713158242,
  0.010465248905162802,
  0.11950586675807841,
  0.04366254542888087,
  0.08507360125278202,
  0.07756550080719044],
 [0.041887804757887934,
  0.11683189221801851,
  0.0,
  0.35272067984661787,
  0.06530337741112337,
  0.0],
 [0.0, 0.0, 0.0, 0.34265644738016127, 0.0491879413607185, 0.17497574035093919],
 [0.03090563825330595,
  0.23868921043480368,
  0.04144349758161898,
  0.0,
  0.3409767584236094,
  0.006653122719221515],
 [0.02568505101388338,
  0.08980737526307651,
  0.03699210010748607,
  0.0,
  0.410700541

In [26]:
import random
list_val = []
list_val1 = []
#rint(a[0][0],avg_val[0])
#print(len(a[0]),len(avg_val))

for j in range(n):
    possible_index = []
    for i in range(6):
        if a[j][i] > avg_val[i]:
            possible_index.append(i)
    if len(possible_index) == 0:
        index = 0
        val = 0
        for i in range(6):
            if a[j][i] > val:
                val = a[j][i]
                index = i
        list_val.append(topic_labels[index])
        list_val1.append(index)
    else:
        rand_val = random.choice(possible_index)
        list_val.append(topic_labels[rand_val])
        list_val1.append(rand_val)
'''    for i in range(6):
        if a[j][i] > val:
            val = a[j][i]
            index = i
    list_val.append(topic_labels[index])
    list_val1.append(index)'''

print(list_val)
print(list_val1)
    

'''    for i in range(6):
        if a[j][i] > avg_val[i]:
            possible_index.append(i)
    if len(possible_index) == 0:
        index = 0
        val = 0
        for i in range(6):
            if a[j][i] > val:
                val = a[j][i]
                index = i
        list_val.append(topic_labels[index])
        list_val1.append(index)
    else:
        rand_val = random.choice(possible_index)
        list_val.append(topic_labels[rand_val])
        list_val1.append(rand_val)
        '''

['party', 'party', 'breakups', 'independence', 'reminiscing', 'breakups', 'party', 'independence', 'reminiscing', 'homesick', 'love', 'party', 'reminiscing', 'reminiscing', 'homesick', 'reminiscing', 'breakups', 'breakups', 'independence', 'reminiscing', 'party', 'homesick', 'love', 'breakups', 'homesick', 'homesick', 'breakups', 'love', 'breakups', 'independence', 'love', 'homesick', 'breakups', 'breakups', 'reminiscing', 'homesick', 'breakups', 'reminiscing', 'party', 'reminiscing', 'independence', 'homesick', 'reminiscing', 'reminiscing', 'love', 'breakups', 'independence', 'independence', 'love', 'love', 'reminiscing', 'party', 'reminiscing', 'party', 'reminiscing', 'homesick', 'love', 'breakups', 'party', 'reminiscing', 'love', 'breakups', 'homesick', 'party', 'love', 'independence', 'party', 'love', 'love', 'party', 'reminiscing', 'love', 'homesick', 'independence', 'homesick', 'party', 'independence', 'breakups', 'reminiscing', 'homesick', 'breakups', 'homesick', 'love', 'party'

'    for i in range(6):\n        if a[j][i] > avg_val[i]:\n            possible_index.append(i)\n    if len(possible_index) == 0:\n        index = 0\n        val = 0\n        for i in range(6):\n            if a[j][i] > val:\n                val = a[j][i]\n                index = i\n        list_val.append(topic_labels[index])\n        list_val1.append(index)\n    else:\n        rand_val = random.choice(possible_index)\n        list_val.append(topic_labels[rand_val])\n        list_val1.append(rand_val)\n        '

In [27]:
df_topics = pd.DataFrame(topic_values,columns = topic_labels)
print(df_topics.head())
songs['label_index'] = list_val1
songs['label'] = list_val

#print(df_topics.head())
print(songs)
#songs.to_csv('C:\\Users\\user1\\taylor_swift_lyrics_updated.csv')

       love  reminiscing  breakups     party  homesick  independence
0  0.054096     0.090519  0.000000  0.462215  0.000000      0.000000
1  0.020685     0.000000  0.085332  0.265040  0.053212      0.000000
2  0.000000     0.000000  0.695891  0.000000  0.000000      0.000000
3  0.000000     0.032521  0.017163  0.000000  0.000000      0.464325
4  0.000000     0.191070  0.082216  0.071819  0.061746      0.149368
               track_title  \
0         ...Ready for It?   
1                       22   
2   A Perfectly Good Heart   
3    A Place In This World   
4             All Too Well   
..                     ...   
89          Wildest Dreams   
90              Wonderland   
91         You Are in Love   
92      You Belong With Me   
93        You're Not Sorry   

                                                                                                                                                                                                                                 

In [28]:
#print(songs.columns)
#print(df_topics.columns)

#df_topics['label_index'] = list_val1
#df_topics['label'] = list_val

df_topics = pd.read_csv('./my_trial.csv',encoding = 'latin-1')

val = df_topics.iloc[ : ,1 : 7].values
df_topics = pd.DataFrame(val,columns = topic_labels)
df_topics['label_index'] = list_val1
df_topics['label'] = list_val
print(df_topics)
#print(df_topics.values)
print(type(df_topics))
#df_topics.to_csv('C:\\Users\\user1\\my_trial.csv')
'''
songs.drop(['track_title'],axis = 1)
#songs = songs.join(df_topics)
print(songs)
'''

        love  reminiscing  breakups     party  homesick  independence  \
0   0.054076     0.090544  0.000000  0.462069  0.000000      0.000000   
1   0.020682     0.000000  0.085081  0.264947  0.053203      0.000000   
2   0.000000     0.000000  0.693841  0.000000  0.000000      0.000000   
3   0.000000     0.032526  0.017110  0.000000  0.000000      0.464084   
4   0.000000     0.191110  0.081971  0.071779  0.061747      0.149292   
..       ...          ...       ...       ...       ...           ...   
89  0.022575     0.031075  0.049223  0.238713  0.065462      0.038045   
90  0.071459     0.164821  0.000000  0.029891  0.063455      0.240476   
91  0.339280     0.000000  0.000000  0.000000  0.009309      0.107773   
92  0.013327     0.117278  0.000000  0.335050  0.155767      0.044563   
93  0.000000     0.000000  0.057599  0.439709  0.000000      0.008507   

    label_index         label  
0             3         party  
1             3         party  
2             2      breaku

"\nsongs.drop(['track_title'],axis = 1)\n#songs = songs.join(df_topics)\nprint(songs)\n"

In [29]:
df_topics.head()

love  reminiscing  breakups     party  homesick  independence  \
0  0.054076     0.090544  0.000000  0.462069  0.000000      0.000000   
1  0.020682     0.000000  0.085081  0.264947  0.053203      0.000000   
2  0.000000     0.000000  0.693841  0.000000  0.000000      0.000000   
3  0.000000     0.032526  0.017110  0.000000  0.000000      0.464084   
4  0.000000     0.191110  0.081971  0.071779  0.061747      0.149292   

   label_index         label  
0            3         party  
1            3         party  
2            2      breakups  
3            5  independence  
4            1   reminiscing

In [30]:
X = df_topics.iloc[ : , : 6].values
Y = df_topics.iloc[ : , 6: 7].values
print(X)
print(Y)

[[0.05407591 0.09054413 0.         0.4620692  0.         0.        ]
 [0.02068213 0.         0.08508058 0.26494674 0.05320312 0.        ]
 [0.         0.         0.69384138 0.         0.         0.        ]
 [0.         0.03252604 0.01711026 0.         0.         0.46408358]
 [0.         0.19111044 0.08197082 0.07177905 0.06174669 0.14929222]
 [0.07350726 0.01046598 0.11916088 0.04369642 0.08504088 0.07753958]
 [0.04190442 0.11685825 0.         0.35255971 0.06531111 0.        ]
 [0.         0.         0.         0.34250787 0.04918535 0.17488919]
 [0.03092904 0.23873937 0.04131508 0.         0.34097811 0.00664018]
 [0.02569452 0.08982431 0.03688247 0.         0.41069593 0.02700783]
 [0.10970127 0.         0.04020091 0.19182311 0.         0.3548223 ]
 [0.05383997 0.1225757  0.03183398 0.2319096  0.03911521 0.        ]
 [0.         0.09321146 0.         0.07445734 0.02373607 0.06857233]
 [0.09059692 0.1546199  0.00971645 0.14388271 0.         0.00491123]
 [0.         0.00606456 0.        

In [31]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.20)
print("X_train",X_train)
print("X_test",X_test)
print("Y_train",Y_train)
print("Y_test",Y_test)

X_train [[0.10441323 0.07595372 0.         0.24985331 0.01209943 0.08274536]
 [0.13473139 0.06936781 0.         0.14670804 0.04263639 0.16704477]
 [0.         0.0595264  0.24044984 0.04129102 0.24507649 0.        ]
 [0.11421967 0.00634319 0.08881799 0.17927888 0.07280469 0.01274079]
 [0.30768546 0.         0.         0.05407049 0.         0.07991705]
 [0.         0.         0.         0.34250787 0.04918535 0.17488919]
 [0.03022195 0.         0.00501119 0.         0.44255648 0.23283554]
 [0.01332729 0.11727844 0.         0.3350505  0.15576742 0.04456262]
 [0.16679263 0.09619331 0.07231541 0.05493072 0.054619   0.03424993]
 [0.04190442 0.11685825 0.         0.35255971 0.06531111 0.        ]
 [0.03141919 0.         0.         0.48800147 0.         0.        ]
 [0.02569452 0.08982431 0.03688247 0.         0.41069593 0.02700783]
 [0.1392589  0.03358922 0.01452403 0.02630682 0.         0.00848144]
 [0.1223987  0.         0.         0.30387899 0.05331087 0.        ]
 [0.         0.56854388 0.

In [32]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

print("X_train",X_train)
print("X_test",X_test)
print("Y_train",Y_train)





print("Y_test",Y_test)


X_train [[ 3.86747863e-01 -9.90437300e-02 -4.71616155e-01  9.58924249e-01
  -5.37514045e-01  6.84895872e-02]
 [ 7.28572847e-01 -1.44809390e-01 -4.71616155e-01  1.60015413e-01
  -3.12602974e-01  7.65878307e-01]
 [-7.90469084e-01 -2.13197563e-01  1.48808220e+00 -6.56489302e-01
   1.17841044e+00 -6.16042837e-01]
 [ 4.97311528e-01 -5.82769048e-01  2.52262360e-01  4.12291952e-01
  -9.04072083e-02 -5.10641354e-01]
 [ 2.67856004e+00 -6.26848019e-01 -4.71616155e-01 -5.57506265e-01
  -6.26628852e-01  4.50916485e-02]
 [-7.90469084e-01 -6.26848019e-01 -4.71616155e-01  1.67657767e+00
  -2.64368541e-01  8.30773235e-01]
 [-4.49728831e-01 -6.26848019e-01 -4.30774324e-01 -9.76307743e-01
   2.63289166e+00  1.31014946e+00]
 [-6.40209281e-01  1.88122808e-01 -4.71616155e-01  1.61881676e+00
   5.20630613e-01 -2.47387067e-01]
 [ 1.09005038e+00  4.16017318e-02  1.17764090e-01 -5.50843365e-01
  -2.24348529e-01 -3.32701387e-01]
 [-3.18013649e-01  1.85202915e-01 -4.71616155e-01  1.75443389e+00
  -1.45598928e-01

In [33]:
#print(Y_train.ravel().shape)

from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=6)

classifier.fit(X_train, Y_train.ravel())


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=6, p=2,
                     weights='uniform')

In [34]:
Y_pred = classifier.predict(X_test)
print(Y_test)
print(Y_pred)
tot = 0
for i in range(len(Y_test)):
    if Y_test[i] == Y_pred[i]:
        tot = tot + 1
print("Accuracy :-   ",((tot/len(Y_pred)*100)),"%")

[[2]
 [1]
 [1]
 [5]
 [1]
 [0]
 [2]
 [1]
 [2]
 [3]
 [0]
 [2]
 [4]
 [4]
 [0]
 [5]
 [1]
 [1]
 [4]]
[0 1 5 5 1 0 2 5 2 3 4 3 3 4 0 4 4 1 4]
Accuracy :-    57.89473684210527 %


In [35]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(Y_test, Y_pred))
print(classification_report(Y_test, Y_pred))

[[2 0 0 0 1 0]
 [0 3 0 0 1 2]
 [1 0 2 1 0 0]
 [0 0 0 1 0 0]
 [0 0 0 1 2 0]
 [0 0 0 0 1 1]]
              precision    recall  f1-score   support

           0       0.67      0.67      0.67         3
           1       1.00      0.50      0.67         6
           2       1.00      0.50      0.67         4
           3       0.33      1.00      0.50         1
           4       0.40      0.67      0.50         3
           5       0.33      0.50      0.40         2

    accuracy                           0.58        19
   macro avg       0.62      0.64      0.57        19
weighted avg       0.75      0.58      0.60        19



In [36]:
vectorizer = TfidfVectorizer(stop_words = stop_words, min_df = 0.1)

In [37]:
import re
def remove(string): 
    pattern = '[0-9]'
    list = [re.sub(pattern, '', i) for i in string] 
    return string


data = input().lower()

# print(data.split('\n'))
df = pd.DataFrame(data.split('\n'))
print(df[0])
# print(df.size,df.shape,df[0].ndim)
# print(df[0])


print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX_",df,"_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
print(df.size,df.shape,df[0].ndim)

tfidf = vectorizer.fit_transform(df[0])
print('WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW')
print(tfidf)
print('WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW')
nmf = NMF(n_components = 6)
topic = nmf.fit_transform(tfidf)
print(topic)

#'''

Knew he was a killer first time that I saw him Wondered how many girls he had loved and left haunted But if he's a ghost, then I can be a phantom Holdin' him for ransom, some Some boys are tryin' too hard, he don't try at all though Younger than my exes, but he act like such a man, so I see nothing better, I keep him forever Like a vendetta-ta I, I, I see how this is gon' go Touch me and you'll never be alone I-Island breeze and lights down low No one has to know In the middle of the night, in my dreams You should see the things we do, baby In the middle of the night, in my dreams I know I'm gonna be with you So I take my time Are you ready for it? Knew I was a robber first time that he saw me Stealing hearts and running off and never sayin' sorry But if I'm a thief, then he can join the heist, and We'll move to an island, and And he can be my jailer, Burton to this Taylor Every love I've known in comparison is a failure I forget their names now, I'm so very tame now Never be the same 

In [42]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(topic)
X_val = scaler.transform(topic)
print(X_val)

[[0. 0. 0. 0. 0. 0.]]


In [43]:
pred_val = classifier.predict(X_val)

In [44]:
print(pred_val)

[2]


In [45]:
print(topic_labels[int(pred_val)])

breakups
